Add an evaluation element 6.5 on public project
SubstraFoundation/referentiel-evaluation-dsrc pull request #96
Opened 2020-10-27 15:38 UTC by ClementMayer

Close #86 
Withdraw analysis from references page 
Add 2 elements about public projects.

2020-10-28 15:22 UTC, bowni requested changes
@ClementMayer :

2020-10-28 15:22 UTC, bowni commented on referentiel_evaluation.md
> +Q6.4 : **Projets public**
```suggestion
---

Q6.4 : **Projets publics**  
```

2020-10-28 15:22 UTC, bowni commented on referentiel_evaluation.md
> +
```suggestion
Il s'agit de s'assurer dans le cadre de projets à destination du grand public de la bonne compréhension et de l'adhésion au projet de la part des administrés concernés. Des contenus pédagogiques doivent être mis en place, destinés à un public n'étant pas familier avec la Data Science, afin de lever les différentes craintes. 

```

2020-10-28 15:22 UTC, bowni commented on referentiel_evaluation.md
> +</details>
Peut-être ajouter ici le guide de référence d'Etalab ? Le rapport de l'ENA ?

2020-10-28 15:22 UTC, bowni commented on referentiel_evaluation.md
> +Dans les cas de figure où les modèles prédictifs que votre organisation élabore sont utilisés dans des cadres de projets publics :
OK je comprends l'idée. Il faut peut-être préciser la notion de projets publics. J'ai l'impression que l'on cherche ici à cibler *les projets des organisations qui relèvent du secteur public* (collectivités territoriales, administrations, autorités administratives indépendantes, structures à missions de service publics...). Le mot "administré" ne va pas suffire, on va avoir aussi ici des citoyens, des bénéficiaires, etc. Peut-être "le public cible", ou "les usagers" ?

2020-11-02 09:00 UTC, natct10 approved these changes
Top les rapports Etalab, merci !

2020-11-03 11:42 UTC, bowni commented on referentiel_evaluation.md
> +- [ ] 6.5.c Nous organisons des concertations et des réunions d'information pour présenter les données et usages utilisés
Quelle est la différence entre enquête à destination du public concerné (6.5.a), et concertations et réunions d'informations (6.5.c) ?

2020-11-03 11:42 UTC, bowni commented on referentiel_evaluation.md
> +- [ ] 6.5.e Nous procédons à la mise en place d'un dépôt public permettant de consulter le code source
C'est un bon point, mais la question qui se pose c'est "le code source de quoi ?". En essayant d'y réfléchir, ça me semble un point assez complexe, je n'ai pas trop d'idée.

2020-11-03 11:42 UTC, bowni commented on referentiel_evaluation.md
> +- [ ] 6.5.e Nous procédons à la mise en place d'un dépôt public permettant de consulter le code source
L'élément d'évaluation s'intitule "Consultation de toutes les parties prenantes", ce qui ne colle pas top avec ces 2 items de réponse. Il faudrait soit revoir l'intitulé de l'élément, soit faire un 2nd élément ?

2020-11-03 11:42 UTC, bowni commented on referentiel_evaluation.md
> +- (Public declaration) [Éthique et responsabilité des algorithmes publics](https://www.etalab.gouv.fr/wp-content/uploads/2020/01/Rapport-ENA-Ethique-et-responsabilit%C3%A9-des-algorithmes-publics.pdf
Mettons peut-être le "ethics toolkit" après les docs officiels Etalab ?

2021-09-30 15:01 UTC, bowni commented
@ClementMayer que souhaites-tu faire de cette issue ?

2021-09-30 15:03 UTC, ClementMayer commented
Je le ferme finalement ce n'est pas très intéressant.

2021-09-30 15:03 UTC, closed without merging